version: '3'

services:
  docs:
    image: ecliptoinc_local_docs
    container_name: ecliptoinc_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./ecliptoinc:/app/ecliptoinc:z
    ports:
      - '9000:9000'
    command: /start-docs
