# Generated by Django 4.2.11 on 2024-04-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_plan_pricing_pricingfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricing',
            name='package',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='B', max_length=100, unique=True),
        ),
    ]
