# Generated by Django 4.2.11 on 2024-04-05 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_remove_pricing_package_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='package',
            field=models.CharField(choices=[('B', 'Basic'), ('P', 'Premium'), ('E', 'Enterprise')], default='B', max_length=100, unique=True),
        ),
    ]
