# Generated by Django 4.2.11 on 2024-04-05 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_pricing_package'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.UniqueConstraint(fields=('plan', 'package'), name='unique_pricing_plan_package'),
        ),
    ]
