# Generated by Django 4.2.11 on 2024-04-05 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_pricing_unique_pricing_plan_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_plan', to='services.category'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('M', 'Monthly'), ('Y', 'Yearly')], default='M', max_length=100, unique=True),
        ),
    ]
