# Generated by Django 4.2.11 on 2024-04-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0010_alter_plan_category_alter_plan_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="pricing",
            name="unique_pricing_plan_package",
        ),
        migrations.AddConstraint(
            model_name="pricing",
            constraint=models.UniqueConstraint(
                fields=("plan", "package"), name="unique_pricing_plan_package"
            ),
        ),
    ]
