# Generated by Django 4.2.11 on 2024-04-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_pricing_unique_pricing_plan_package_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pricing',
            name='unique_pricing_plan_package',
        ),
        migrations.AlterField(
            model_name='pricing',
            name='package',
            field=models.CharField(choices=[('B', 'Basic'), ('P', 'Premium'), ('E', 'Enterprise')], default='B', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='pricing',
            constraint=models.UniqueConstraint(fields=('plan', 'package'), name='unique_pricing_plan_package'),
        ),
    ]
