# Generated by Django 4.2.11 on 2024-04-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_pricing_unique_pricing_plan_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
