# Generated by Django 4.2.11 on 2024-04-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_pricing_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
