# Generated by Django 4.2.11 on 2024-04-12 13:31

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="salary",
            field=django.contrib.postgres.fields.ranges.DecimalRangeField(
                [
                    models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
                    models.DecimalField(max_digits=10, decimal_places=2, default=0.00),
                ],
                default=[0.00, 0.00],
            ),
        ),
    ]
