# Generated by Django 4.2.11 on 2024-04-12 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_position_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='type',
            field=models.CharField(choices=[('R', 'Rmote'), ('F', 'Full Time')], default='R', max_length=1),
        ),
    ]
