# Generated by Django 4.2.11 on 2024-04-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_position_detail_position_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='type',
            field=models.CharField(choices=[('R', 'Rmote'), ('F', 'Full Time'), ('C', 'Contract'), ('I', 'Internship')], default='R', max_length=1),
        ),
    ]
